### ISSUE TITLE
ExtractFull progress file array remains empty

### ISSUE THREAD

**Issue by Riuujin** [quentinrossetti/node-7z#15]
I am using the following code:
```javascript
var archive = new Zip();
archive.extractFull('c:\\archive.rar', 'c:\\destination', {
 wildcard: ['*.jpg', '*.png'],
  r: true 
})
.progress(function (files) {
  // Do stuff with files...
})
.then(function () {
  // Do stuff...
});
```

The file is extracted successfully but the files array of the progress function remains empty

**Comment by Riuujin** [comment]
Seems this more of a 7-zip issue as it doesn't output the files extracted.

**Comment by dallasacook** [comment]
Hey @Riuujin, I seem to be experiencing the same exact issue as you have described above. 

I am using the latest version of 7-zip and node-7z 0.4.0 in CentOS 6.7.

When I use both the the extract and extractFull methods, the progress function's files array is always empty no matter if the extraction is successful or not. I've made sure that this is not a permissions issue.

Have you been able to discover what your issue was? How did you address the problem?

**Comment by Riuujin** [comment]
@dallasacook For my self I have an ugly workaround that i simply also do a "list" call to get all the files.
That way I can at least tell what was extracted if there was no error. 

As for the cause of the issue it's because 7-zip doesn't output the extracted files for its command line tool. node-7z just parses the output provided by this tool so it doesn't get a file list.,

**Comment by dallasacook** [comment]
How strange. I'm working on a similar "list" workaround using the fs module to grab the newly extracted files from the directory as we speak. 

Thank you so much for the quick reply @Riuujin.
